## Setup

In [1]:
import torch



## Random integer tensor

In [2]:
randint = torch.randint(-100, 100, (6,)) 
# the (6,) is the shape of the tensor/array - 1D array with 6 elements
randint

tensor([-77,   7,  39,  85, -56, -56])

## Torch syntax examples

# TORCH SYNTAX EXAMPLES

In [3]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

## Tensor from values

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Zero tensor

In [5]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## Ones tensor

In [6]:
#torch empty creates a tensor without initializing the values, so it may contain random values
input = torch.empty(2,3)
input

tensor([[1.1548e-13, 1.7768e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

## Empty tensor

In [7]:
arange1 = torch.arange(10)
arange2 = torch.arange(1,100,2)
print(arange1)
print(arange2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])


## Range tensors

In [8]:
linspace = torch.linspace(1,10,steps=5)
linspace

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

## Linspace

In [ ]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

: 

## Logspace

# difference between logspace and linspace

the `torch.logspace` function generates a sequence of numbers that are spaced evenly on a logarithmic scale, while the `torch.linspace` function generates a sequence of numbers that are spaced evenly on a linear scale.


## torch.linspace (linear spacing)

Think of it like walking in equal steps.

If you go from -10 to 10 with 5 steps, you get:

-10 → -5 → 0 → 5 → 10

Every step moves the same distance.

        Key idea:

        Equal differences between numbers
        Like evenly spaced marks on a ruler
        
## torch.logspace (logarithmic spacing)

Think of it like growing by multiplication instead of addition.

Instead of adding the same amount each time, you multiply.

So it might look like:

0.0001 → 0.01 → 1 → 100 → 10000

The jumps get bigger and bigger.

        Key idea:

        Equal ratios between numbers
        Not equal gaps, but equal “growth rate”
        Simple analogy
        linspace = stairs
# Simple analogy
## linspace = stairs 
### You climb evenly:

    same height per step
    linspace → plotting, simple ranges
## logspace = escalator 
### You speed up as you go:

    slow at first, then rapidly increases
    logspace → learning rates, loss curves, exponential behavior

## Logspace versus linspace

In [ ]:
import torch
import matplotlib.pyplot as plt

lin = torch.linspace(-10, 10, steps=5)
log = torch.logspace(-10, 10, steps=5)

print(lin)
print(log)

plt.figure()

# linear function
plt.plot(lin.numpy(), lin.numpy(), marker="o", label="y = x")

# exponential function (correct interpretation)
plt.plot(lin.numpy(), (10 ** lin).numpy(), marker="o", label="y = 10^x")

plt.legend()
plt.xlabel("x")
plt.ylabel("y")
plt.yscale("log")  # optional but makes exponential visible

plt.show()

tensor([-10.,  -5.,   0.,   5.,  10.])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


## Plotting example

In [ ]:
# 5 by 5 matrix with a diagonal line
eye = torch.eye(5)
print(eye)

#reversed diagonal
eye = eye.flip(1)
print("reversed diagonal\n", eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
reversed diagonal
 tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])


## Eye and flipped diagonal

In [ ]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[4607182418800017408, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408,                   1]])

## Empty like

## Placeholder

## Placeholder