In [53]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device, 'is running')

cuda is running


# Testing the difference between the GPU and CPU versions of the code

In [54]:
start_time = time.time()
#matrix operaetions here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0015704632


## which is better? numpy on the CPU or torch is in cuda on the GPU?

In [55]:
# .to(device) moves the tensor to the GPU if available, otherwise it stays on the CPU
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)
#-------------------torch version-----------------------
start_time = time.time()
# time.time() → “what time is it right now (in seconds)”
 
rand = (torch_rand1 @ torch_rand2) #@ is the matrix multiplication operator in Python.

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time :.8f}")
## ----------------numpy version-----------------------
start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time :.8f}")

0.01584411
0.16202354


C:\Users\User\AppData\Local\Temp\ipykernel_36020\2465063966.py:19: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [56]:
import time

# .to(device) moves the tensor to the GPU if available, otherwise it stays on the CPU
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

# ------------------- torch version -----------------------
start_time = time.perf_counter()

rand = (torch_rand1 @ torch_rand2)

end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

# ------------------- numpy version -----------------------
start_time = time.perf_counter()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.03290840
0.12052250


C:\Users\User\AppData\Local\Temp\ipykernel_36020\299340977.py:21: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


### perf_counter is better than time.time() for measuring elapsed time, but time.time() is good enough for this test.

time.time() → “what time is it?”


perf_counter() → “how long has passed?”

In [57]:
import time

# .to(device) moves the tensor to the GPU if available, otherwise it stays on the CPU
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

# ------------------- torch version -----------------------
start_time = time.perf_counter()

rand = (torch_rand1 @ torch_rand2)

end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

# ------------------- numpy version -----------------------
start_time = time.perf_counter()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.01907350
0.09763330


C:\Users\User\AppData\Local\Temp\ipykernel_36020\299340977.py:21: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [58]:
import time

# .to(device) moves the tensor to the GPU if available, otherwise it stays on the CPU
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

# ------------------- torch version -----------------------
start_time = time.perf_counter()

rand = (torch_rand1 @ torch_rand2)

end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

# ------------------- numpy version -----------------------
start_time = time.perf_counter()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.perf_counter()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.01483710
0.09721960


C:\Users\User\AppData\Local\Temp\ipykernel_36020\1852368107.py:21: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [59]:
%%time 
# time how long it takes to run the cell
import time

start_time = time.time()
# matrix operations here
zeros = torch.zeros(10000, 10000)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time :.8f}")

0.01418495
CPU times: total: 125 ms
Wall time: 15.2 ms


In [60]:
%timeit torch.zeros(1000, 1000)

44.9 μs ± 2.97 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [88]:
# [torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the functions in the torch library that we have covered so far)

# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9]) # they need to add up to 1 or 100%
# 10 percent chance we get a 0 and 90 percent to get a 1
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomtal distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
# replacement controlls whether you are allowed to pick the same item more than once
print(samples)

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])


In [87]:
# [torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the functions in the torch library that we have covered so far)

# Define a probability tensor
probabilities = torch.tensor([0.1, 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1 ]) # they need to add up to 1 or 100%
# 10 percent chance we get a 0 and 90 percent to get a 1
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomtal distribution
samples = torch.multinomial(probabilities, num_samples=10)
# replacement controlls whether you are allowed to pick the same item more than once
print(samples)

tensor([3, 6, 7, 9, 2, 5, 0, 8, 4, 1])


In [ ]:
# concatenate
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [ ]:
#triangle
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [91]:
# triangle upper just the opposite of tril
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [ ]:
# masked fill is a function that fills a tensor with a specified value 
# where a given condition is true. In this case,
# we are filling the tensor with negative infinity where the lower 
# triangular part of the tensor is zero.

#torch.exp is a function that calculates the exponential of each element in the tensor.

out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
print(out)
print(torch.exp(out))

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])
tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [93]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
# transpose
input = torch.zeros(2,3,4)
out = input.transpose(0,2) # swapping the index 0 and 2
out.shape #  out.shape is the dimensions of the tensor after the transpose operation

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])