In [3]:
import torch

In [ ]:
randint = torch.randint(-100,100, (6,))
randint
# torch.randint(low, high, size)
# -100 — minimum value (inclusive)
# 100 — maximum value (exclusive), so the highest number you'll get is 99
# (6,) — shape of the tensor, meaning a 1D tensor with 6 random integers

tensor([-31,  23,  10,  76,   4, -28])

# Tensor is just data in multiple dimensions

In [21]:
tensor = torch.tensor([[0.1, 1.2],[2.2,3.1],[4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [33]:
zeros = torch.zeros(2,3)
ones = torch.ones(4,5)
print(zeros)
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [80]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])